install.packages("imager")

earpics<-list.files("I:/00_Manuscripts/0Avian aquatic hearing project/_0Manuscript/Measurement definitions/pics", full.names = TRUE)
library(gtools)
earpics<-mixedsort(earpics)#sort keeping numerical order
earpics_short<-list.files("I:/00_Manuscripts/0Avian aquatic hearing project/_0Manuscript/Measurement definitions/pics", full.names = FALSE)
earpics_short<-mixedsort(earpics_short)#sort keeping numerical order
length(earpics)

#for (i in earpics){
#  assign(earpics[i],load.image(earpics[i]))
#}
#assign(earpics_short[1]<-load.image(earpics[1])
P1<-load.image(earpics[1])
P2<-load.image(earpics[2])
P3<-load.image(earpics[3])
P4<-load.image(earpics[4])
P5<-load.image(earpics[5])
P6<-load.image(earpics[6])
P7<-load.image(earpics[7])
P8<-load.image(earpics[8])
P9<-load.image(earpics[9])
P10<-load.image(earpics[10])
P11<-load.image(earpics[11])
P12<-load.image(earpics[12])
P13<-load.image(earpics[13])
P14<-load.image(earpics[14])
P15<-load.image(earpics[15])
P16<-load.image(earpics[16])

dat<-rbind(P1,P2)

par(mfrow=c(4,4))
par(mar = c(0,0,3,0))

plot(P1, axes = FALSE)
title(main = paste0(earpics_short[1],"_"), cex.main = 2)
plot(P2, axes = FALSE)
title(main = paste0(earpics_short[2],"_"), cex.main = 2)
plot(P3, axes = FALSE)
title(main = paste0(earpics_short[3],"_"), cex.main = 2)
plot(P4, axes = FALSE)
title(main = paste0(earpics_short[4],"_"), cex.main = 2)
plot(P5, axes = FALSE)
title(main = paste0(earpics_short[5],"_"), cex.main = 2)
plot(P6, axes = FALSE)
title(main = paste0(earpics_short[6],"_"), cex.main = 2)
plot(P7, axes = FALSE)
title(main = paste0(earpics_short[7],"_"), cex.main = 2)
plot(P8, axes = FALSE)
title(main = paste0(earpics_short[8],"_"), cex.main = 2)
plot(P9, axes = FALSE)
title(main = paste0(earpics_short[9],"_"), cex.main = 2)
plot(P10, axes = FALSE)
title(main = paste0(earpics_short[10],"_"), cex.main = 2)
plot(P11, axes = FALSE)
title(main = paste0(earpics_short[11],"_"), cex.main = 2)
plot(P12, axes = FALSE)
title(main = paste0(earpics_short[12],"_"), cex.main = 2)
plot(P13, axes = FALSE)
title(main = paste0(earpics_short[13],"_"), cex.main = 2)
plot(P14, axes = FALSE)
title(main = paste0(earpics_short[14],"_"), cex.main = 2)
plot(P15, axes = FALSE)
title(main = paste0(earpics_short[15],"_"), cex.main = 2)

pdf("I:/Analysis_plots/earmeasures_panel2.pdf",  width = 10, height = 10)
dev.off()

getwd()

